name: "[CI] Continuous Integration"

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## [Commom_CI_Steps]
      - uses: actions/checkout@v3  
      - name: "debug"
        run: | 
         "ls -la"
         echo "Segundo comando de debug"
         echo "Terceiro comando de debug"
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Lint"
        run: "npm run lint"

