name: "[CI] Continuous Integration"

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Lint"
        run: "npm run lint"

  create-pull-request:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: "Create Pull Request"
        uses: actions/create-pull-request@v5
        with:
          title: "Lint fix"
          body: "This pull request fixes the lint errors found in the last commit."
          target: "main"
